name: ArrowSquid tag
on:
  workflow_dispatch:

jobs:
  test:
    name: Tag ArrowSquid npm packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Write npm credentials
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> common/config/rush/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> common/config/rush/.npmrc-publish
          cd common/config/rush && npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Set tags
        run: cd common/config/rush && ../../../ops/npm-tag-arrowsquid.sh
