name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: release tag (next, latest)
        required: false
        default: next

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release

      - name: Write npm credentials
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> common/config/rush/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> common/config/rush/.npmrc-publish
          cd common/config/rush && npm whoami
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

#      - name: e2e tests
#        working-directory: test/e2e-suite
#        run: ./run.sh

      - name: Install dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build project
        run: node common/scripts/install-run-rush.js build

      - name: Publish npm packages
        run: node common/scripts/install-run-rush.js publish --include-all --version-policy public --publish --tag $TAG
        env:
          TAG: ${{ github.event.inputs.tag }}
