on:
  workflow_dispatch:
    inputs:
      tag:
        description: release tag (next, latest)
        required: false
        default: next

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
#      - name: e2e tests
#        working-directory: test/e2e-suite
#        run: ./run.sh
      - name: Publish npm packages
        run: node common/scripts/install-run-rush.js publish --include-all --publish --tag $TAG
        env:
          TAG: ${{ github.event.inputs.tag }}
